# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jenyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='genreS',
        ),
    ]
